GET http://localhost:4000/posts
###
GET http://localhost:4000/users
###
POST http://localhost:4000/users
Content-Type: application/json

{
  "username": "Tim Lee",
  "password": "password"
}
###
POST http://localhost:4001/users/login
Content-Type: application/json

{
  "username": "Tim Lee",
  "password": "password"
}

###
POST  http://localhost:4001/token
Content-Type: application/json

{
  "token": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbSBMZWUiLCJpYXQiOjE2NzU2MTAwNzd9.neaKYy0evEN0-s03teLBdGJX0qSrxBx48lFg_LDmUSU"
}
###
DELETE http://localhost:4001/logout
Content-Type: application/json

{
  
}

###
GET http://localhost:4001/posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbSBMZWUiLCJpYXQiOjE2NzU2MTAwOTksImV4cCI6MTY3NTYxMDExOX0.GKCvquWc-kglOfikXxZMMNtqkjnul5gCsmkOptTVoxU
###
GET http://localhost:4001/posts
authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6IlRpbSBMZWUiLCJpYXQiOjE2NzU2MDkwMDgsImV4cCI6MTY3NTYwOTAyOH0.25D15ADccZ-iOx-UZ6vqI_ndQDJP3UeHH6kt25zxToc 